#!/usr/bin/env python3
"""
Build Lume/Data/etf_holdings.json from public top-holdings data.

Inputs
  tools/etf_manifest.json         list of funds (symbol, name, category) + asOf, topN
  tools/holdings_raw/<SYM>.tsv    per-fund holdings: symbol<TAB>name<TAB>weight%   (one row per holding)
  tools/sectors.json              ticker -> sector map

Output
  Lume/Data/etf_holdings.json     the on-device look-through dataset

Refreshing the data
  Re-pull each fund's top holdings (issuer site or a public aggregator) into the
  .tsv files, bump "asOf" in the manifest, then run:  python3 tools/build_holdings.py
Nothing here runs at app runtime — the app only reads the generated JSON, so the
look-through stays fully on-device.
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(ROOT)
RAW_DIR = os.path.join(ROOT, "holdings_raw")
# In the app repo the dataset is bundled under Lume/Data; in the standalone
# public data repo it lives at the repo root. Same script, both layouts.
_APP_DATA = os.path.join(REPO, "Lume", "Data")
OUT = os.path.join(_APP_DATA, "etf_holdings.json") if os.path.isdir(_APP_DATA) \
    else os.path.join(REPO, "etf_holdings.json")


def parse_weight(s):
    s = s.strip().replace("%", "").replace(",", "")
    if not s:
        return None
    try:
        return float(s) / 100.0
    except ValueError:
        return None


def load_raw(symbol):
    path = os.path.join(RAW_DIR, f"{symbol}.tsv")
    if not os.path.exists(path):
        return None
    rows = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line.strip():
                continue
            parts = line.split("\t")
            if len(parts) < 3:
                continue
            sym, name, weight = parts[0].strip().upper(), parts[1].strip(), parse_weight(parts[2])
            if not sym or weight is None:
                continue
            rows.append((sym, name, weight))
    return rows


def main():
    manifest = json.load(open(os.path.join(ROOT, "etf_manifest.json"), encoding="utf-8"))
    sectors = json.load(open(os.path.join(ROOT, "sectors.json"), encoding="utf-8"))
    as_of = manifest.get("asOf", "")
    top_n = int(manifest.get("topN", 15))

    out_funds = []
    missing = []
    for entry in manifest["funds"]:
        sym = entry["symbol"].upper()
        raw = load_raw(sym)
        if not raw:
            missing.append(sym)
            continue
        raw.sort(key=lambda r: r[2], reverse=True)
        holdings = []
        for hsym, hname, weight in raw[:top_n]:
            holdings.append({
                "symbol": hsym,
                "name": hname,
                "weight": round(weight, 5),
                "sector": sectors.get(hsym, "Unclassified"),
            })
        out_funds.append({
            "symbol": sym,
            "name": entry["name"],
            "category": entry.get("category", ""),
            "asOf": as_of,
            "holdings": holdings,
        })

    payload = {
        "note": ("Top-holding snapshots for on-device look-through, generated by "
                 "tools/build_holdings.py from public data. Weights beyond the listed "
                 "holdings are treated as a diversified remainder. Refresh periodically."),
        "asOf": as_of,
        "funds": out_funds,
    }
    with open(OUT, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, ensure_ascii=False)
        f.write("\n")

    unclassified = sorted({
        h["symbol"] for fund in out_funds for h in fund["holdings"]
        if h["sector"] == "Unclassified"
    })
    print(f"Wrote {len(out_funds)} funds -> {os.path.relpath(OUT, REPO)}")
    if missing:
        print(f"  Skipped (no raw file): {', '.join(missing)}")
    if unclassified:
        print(f"  Unclassified tickers (add to sectors.json): {', '.join(unclassified)}")


if __name__ == "__main__":
    sys.exit(main())
